
CREATE TABLE ROL(id INT AUTO_INCREMENT PRIMARY KEY,
tipo_rol VARCHAR (50) NOT NULL); -- DENTRO DE ESTA TABLA SE ALMACENAN LOS ROLES QUE HAY PARA CADA USUARIO

CREATE TABLE USUARIO(
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR (50) NOT NULL,
apellido_paterno VARCHAR (50) NOT NULL,
apellido_materno VARCHAR (50) NOT NULL, 
matricula VARCHAR (50) NOT NULL,
nivel_academico INT,
id_rol INT NOT NULL,
FOREIGN KEY (id_rol) REFERENCES ROL(id)); -- LA INFORMACION DE LOS USUARIOS SE ALMACENA EN LA TABLA


CREATE TABLE TEMAS(id INT AUTO_INCREMENT PRIMARY KEY,
tnombre VARCHAR (50) NOT NULL,
nivel int not null); -- DENTRO DE ESTA TABLA SE ALMACENA LA INFORMACION DE LOS TEMAS Y SUBTEMAS,RAMAS DISCIPLINARIAS Y RAMAS.

CREATE TABLE BANCO_PREGUNTAS(id INT AUTO_INCREMENT PRIMARY KEY,
pregunta VARCHAR (50) NOT NULL,
respuesta VARCHAR (50) NOT NULL,
id_tema INT NOT NULL,
FOREIGN KEY (id_tema) REFERENCES TEMAS(id)); -- DENTRO DE ESTA TABLA SE ALMACENA EL BANCO DE PREGUNTAS DE LOS DISTINTOS TEMAS QUE SE UTILIZARAN PARA EL CUESTIONARIO.

CREATE TABLE RELACION_PROFESOR(id INT AUTO_INCREMENT PRIMARY KEY,
id_profesor INT NOT NULL,
FOREIGN KEY(id_profesor) REFERENCES usuario(id),
id_alumno INT NOT NULL,
FOREIGN KEY(id_alumno) REFERENCES usuario(id)); -- AQUI SE ALMACENA LA RELACION ENTRE EL PROFESOR Y EL ALUMNO, PARA QUE SOLO PUEDA VER LAS CALIFICACIONES DE SU ALUMNO

CREATE TABLE RELACION_PRIMARIA(id INT AUTO_INCREMENT PRIMARY KEY,
id_padre INT NOT NULL,
FOREIGN KEY(id_padre) REFERENCES temas(id),
id_hijo INT NOT NULL,
FOREIGN KEY(id_hijo) REFERENCES temas(id)); -- DENTRO DE ESTA TABLAS SE ALMACENAN LA RELACION DE LOS TEMAS SOBRE CUAL ES PADRE Y CUAL ES HIJO.

CREATE TABLE RELACION_SECUNDARIA(id INT AUTO_INCREMENT PRIMARY KEY,
id_padre INT NOT NULL,
FOREIGN KEY(id_padre) REFERENCES temas(id),
id_hijo INT NOT NULL,
FOREIGN KEY(id_hijo) REFERENCES temas(id)); 

CREATE TABLE cuestionario(id INT AUTO_INCREMENT PRIMARY KEY,
id_alumno INT NOT NULL,
FOREIGN KEY(id_alumno) REFERENCES usuario(id),
porcentaje INT NOT NULL); --DENTRO DE ESTA TABLA SE ALMACENA EL CONOCIMIENTO GENERADO, EL ALUMNO A QUE HACE REFERENCIA Y ID DEL CUESTIOANRIO GENERADO.

CREATE TABLE historial_alumno(id INT AUTO_INCREMENT PRIMARY KEY,
id_pregunta INT NOT NULL,
FOREIGN KEY(id_pregunta) REFERENCES BANCO_PREGUNTAS(id),
id_cuestionario INT NOT NULL,
FOREIGN KEY(id_cuestionario) REFERENCES cuestionario(id),
drespuesta VARCHAR(50) NOT NULL); -- DENTRO DE ESTA TABLA SE ALMACENA EL ID DE LAS PREGUNTAS REALIZADAS APARTIR DEL ID DEL HISTORIAL Y SI ESTA BIEN O MAL.

-- 
CREATE TABLE TESTEO(id INT AUTO_INCREMENT PRIMARY KEY,
fecha date NOT NULL,
variable1 INT NOT NULL ,
variable2 INT NOT NULL ,
variable3 INT NOT NULL,
resultado INT NOT NULL ); -- AQUI SE GUARDAN LAS PROPIEDADES DEL TESTEO DE LA ESTRUCTURA.